[package]
name = "xcl"
version = "0.1.0"
authors = ["Devdutt Shenoi <devdutt@outlook.in>"]
edition = "2018"

[dependencies]
lalrpop-util = "0.18.1"
regex = "1"

[build-dependecies]
lalrpop = {version="0.18.1", features=["lexer"] }
